latest

diff --git a/autovenv/python-build/autovenv-python-build b/autovenv/python-build/autovenv-python-build
--- a/autovenv/python-build/autovenv-python-build
+++ b/autovenv/python-build/autovenv-python-build
@@ -899,7 +899,7 @@ build_package_micropython() {
     "$MAKE" $MAKE_OPTS
     cd ../ports/unix
     "$MAKE" $MAKE_OPTS axtls
-    "$MAKE" $MAKE_OPTS CFLAGS_EXTRA="-DMICROPY_PY_SYS_PATH_DEFAULT='\"${PREFIX_PATH}/lib/micropython\"'"
+    "$MAKE" $MAKE_OPTS CFLAGS_EXTRA="-DMICROPY_PY_SYS_PATH_DEFAULT='\"${PREFIX_PATH}/lib/micropython\"' $CFLAGS_EXTRA"
     "$MAKE" install $MAKE_INSTALL_OPTS PREFIX="${PREFIX_PATH}"
     ln -fs micropython "${PREFIX_PATH}/bin/python"
     mkdir -p "${PREFIX_PATH}/lib/micropython"
@@ -1322,14 +1322,18 @@ configured_with_package_dir() {
 }
 
 use_homebrew() {
+  is_mac || return 1
   # unless Homebrew is at the default /usr/local, need to add its paths to
   # compiler search to be able to use non-keg-only deps from there
-  if command -v brew &>/dev/null; then
+  if is_mac && command -v brew &>/dev/null; then
     local brew_prefix="$(brew --prefix 2>/dev/null || true)"
     # /usr/local/lib:/usr/lib is the default library search path
     if [[ -n $brew_prefix && $brew_prefix != "/usr" && $brew_prefix != "/usr/local" ]]; then
       export CPPFLAGS="${CPPFLAGS:+${CPPFLAGS% } }-I${brew_prefix}/include"
-      export LDFLAGS="${LDFLAGS:+${LDFLAGS% } }-L${brew_prefix}/lib"
+      export LDFLAGS="${LDFLAGS:+${LDFLAGS% } }-L${brew_prefix}/lib -Wl,-rpath,${brew_prefix}/lib"
+      # `python-config` ignores LDFLAGS envvar. Adding to LIBS is the only way to add extra stuff
+      # to `python-config --ldflags` output
+      export LIBS="${LIBS:+${LIBS% } }-L${brew_prefix}/lib -Wl,-rpath,${brew_prefix}/lib"
     fi
   fi
 }
@@ -1340,6 +1344,7 @@ needs_yaml() {
 }
 
 use_homebrew_yaml() {
+  is_mac || return 1
   local libdir="$(brew --prefix libyaml 2>/dev/null || true)"
   if [ -d "$libdir" ]; then
     echo "python-build: use libyaml from homebrew"
@@ -1383,6 +1388,7 @@ has_broken_mac_readline() {
 }
 
 use_homebrew_readline() {
+  is_mac || return 1
   if ! configured_with_package_dir "python" "readline/rlconf.h"; then
     local libdir="$(brew --prefix readline 2>/dev/null || true)"
     if [ -d "$libdir" ]; then
@@ -1423,6 +1429,7 @@ has_broken_mac_openssl() {
 }
 
 use_homebrew_openssl() {
+  is_mac || return 1
   command -v brew >/dev/null || return 1
   for openssl in ${PYTHON_BUILD_HOMEBREW_OPENSSL_FORMULA:-openssl}; do
     local ssldir="$(brew --prefix "${openssl}" || true)"
@@ -1522,6 +1529,7 @@ build_package_verify_openssl() {
 }
 
 use_homebrew_zlib() {
+  is_mac || return 1
   local brew_zlib="$(brew --prefix zlib 2>/dev/null || true)"
   if [ -d "$brew_zlib" ]; then
     echo "python-build: use zlib from homebrew"
@@ -1541,6 +1549,7 @@ use_xcode_sdk_zlib() {
 }
 
 use_homebrew_tcltk() {
+  is_mac || return 1
   # get the version from the folder that homebrew versions
   local tcltk_libdir="$(brew --prefix tcl-tk 2>/dev/null || true)"
   if [ -d "$tcltk_libdir" ]; then
@@ -1598,7 +1607,9 @@ get_tcltk_flag_from() {
 }
 
 use_tcltk() {
-  local tcltk_libdir="$(brew --prefix tcl-tk 2>/dev/null || true)"
+  if is_mac; then
+    local tcltk_libdir="$(brew --prefix tcl-tk 2>/dev/null || true)"
+  fi
   local tcl_tk_libs="$(get_tcltk_flag_from "$PYTHON_CONFIGURE_OPTS")"
 
   # if tcltk_ops_flag is in PYTHON_CONFIGURE_OPTS, use user provided tcltk
@@ -1626,10 +1637,19 @@ build_package_auto_tcltk() {
   fi
 }
 
+# extglob must be set at parse time, not at runtime
+# https://stackoverflow.com/questions/49283740/bash-script-throws-syntax-errors-when-the-extglob-option-is-set-inside-a-subsh
+#
+# The function is *parsed* with "extglob" only if an outer `shopt -s exglob`
+# exists; at *runtime* you still need to activate it *within* the function.
+#
+shopt -s extglob
 apply_python_patch() {
   local patchfile
+  # needed at runtime
+  shopt -s extglob
   case "$1" in
-  Python-* | jython-* | pypy-* | stackless-* )
+  Python-* | jython-* | pypy-* | pypy[0-9].+([0-9])-* | stackless-* )
     patchfile="$(mktemp "${TMP}/python-patch.XXXXXX")"
     cat "${2:--}" >"$patchfile"
 
@@ -1638,7 +1658,9 @@ apply_python_patch() {
     patch -p$striplevel --force -i "$patchfile"
     ;;
   esac
+  shopt -u extglob
 }
+shopt -u extglob
 
 build_package_symlink_version_suffix() {
   if [[ "$CONFIGURE_OPTS $PYTHON_CONFIGURE_OPTS" == *"--enable-framework"* ]]; then
@@ -1699,7 +1721,7 @@ verify_python() {
 try_python_module() {
   if ! "$PYTHON_BIN" -c "import $1" 1>/dev/null 2>&1; then
     { colorize 1 "WARNING"
-      echo ": The Python $1 extension was not compiled. Missing the ${2:-$1}?"
+      echo ": The Python $1 extension was not compiled${3:+ $3}. Missing the ${2:-$1}?"
       return 0
     } >&3
   fi
@@ -1780,9 +1802,14 @@ build_package_verify_py27() {
 build_package_verify_py30() {
   verify_python "${2:-3.0}"
   try_python_module "bz2" "bzip2 lib"
+  try_python_module "curses" "ncurses lib"
+  try_python_module "ctypes" "libffi lib"
   try_python_module "readline" "GNU readline lib"
   verify_python_module "ssl" "OpenSSL lib"
   try_python_module "sqlite3" "SQLite3 lib"
+  if [[ -n $DISPLAY ]]; then
+    try_python_module "tkinter" "Tk toolkit" "and GUI subsystem has been detected"
+  fi
   verify_python_module "zlib" "zlib"
 }
 
@@ -1799,6 +1826,7 @@ build_package_verify_py32() {
 # Post-install check for Python 3.3.x
 build_package_verify_py33() {
   build_package_verify_py32 "$1" "${2:-3.3}"
+  try_python_module "lzma" "lzma lib"
 }
 
 # Post-install check for Python 3.4.x
@@ -1839,6 +1867,11 @@ build_package_verify_py310() {
 # Post-install check for Python 3.11.x
 build_package_verify_py311() {
   build_package_verify_py310 "$1" "${2:-3.11}"
+}
+
+# Post-install check for Python 3.12.x
+build_package_verify_py312() {
+  build_package_verify_py311 "$1" "${2:-3.12}"
 }
 
 # Post-install check for Python 3.x rolling release scripts
@@ -2130,7 +2163,7 @@ if [[ "$CONFIGURE_OPTS $PYTHON_CONFIGURE_OPTS" == *"--enable-universalsdk"* ]]; 
     exit 1
   fi
   package_option python configure --enable-universalsdk=/
-  if [[ "$CONFIGURE_OPTS $PYTHON_CONFIGURE_OPTS" != *"--enable-universal-archs"* ]]; then
+  if [[ "$CONFIGURE_OPTS $PYTHON_CONFIGURE_OPTS" != *"--with-universal-archs"* ]]; then
     # in CPython's configure.ac, --with-universal-archs defaults to 'intel' which means i386 + x86_64
     # since 2.7.5 and 3.3.0 -- i.e. in all non-EOL versions
     # Apple Silicon cannot build these, in it, it rather makes sense to default to Universal2 binaries
